### ISSUE TITLE
Animation in service page is not working

### ISSUE THREAD

**Issue by jDramaix** [ArcBees/arcbees-website#130]
Maybe I'm wrong but if I remember correctly, there was an animation explaining our agile process in the middle of this page: http://www.arcbees.com/#!/services

This animation is not working anymore

**Comment by christiangoudreau** [comment]
It's there :D

**Comment by jDramaix** [comment]
This one ?

![image](https://cloud.githubusercontent.com/assets/1102761/5757795/fb644e06-9cbe-11e4-82d2-e2d884920ef1.png)

Nothing move for me

**Comment by christiangoudreau** [comment]
Browser version, video? Is it chrome that is bugged again? Try with Safari

**Comment by jDramaix** [comment]
The last one: Chrome Version 39.0.2171.99 (64-bit)
The animation works with safari and Firefox. For the video, my screenshot is enough as nothing move :)

**Comment by christiangoudreau** [comment]
mine is .95 hum

**Comment by christiangoudreau** [comment]
Update to .99, still fine.

weird

**Comment by jasonlemay** [comment]
Instead of using issues, could we use only the Jira board for now, otherwise we will end up with duplicated things or will miss something : https://arcbees.atlassian.net/secure/RapidBoard.jspa?rapidView=5&view=detail

**Comment by olafleur** [comment]
Should we close that issue?

**Comment by jasonlemay** [comment]
Yes let's close it!
