### ISSUE TITLE
New site doesn't work with IE9

### ISSUE THREAD

**Issue by jDramaix** [ArcBees/arcbees-website#132]
A lot of people working in Bank and administration (potentiel client) are still stuck with IE9. So I think we should maybe at least make the site readable (without any animations if they are not supported by IE9)

![capture](https://cloud.githubusercontent.com/assets/1102761/5757830/740a2880-9cbf-11e4-8498-7ccd1248aae0.PNG)

**Comment by jasonlemay** [comment]
I'll be on cross-browser issues today!

**Comment by jDramaix** [comment]
\o/

**Comment by christiangoudreau** [comment]
Yeah, no animation for IE9, that will be the simplest solution :D

**Comment by olafleur** [comment]
Finally, @jasonlemay , did we manage to make it work in IE9?

**Comment by jasonlemay** [comment]
@olafleur Should be fixed by now ... I can't access the website through my VM, it should be tested and if it's still broken, added as an issue to the AW Jira's board. I'm on it!
