### ISSUE TITLE
The support page does not load when uBlock is installed.

### ISSUE THREAD

**Issue by olafleur** [ArcBees/arcbees-website#194]
It's probably because there is A/B testing on that page so, the loading of the page depends on the Analytics call. However, it seems to be blocked by uBlock.

I guess we could have a default page for that case?

**Comment by jasonlemay** [comment]
If you are browsing the web with a tool that modify your browsing experience, you should expect that kind of thing to happen. We should not start developing workarounds because X plugin in a browser is causing problems : it will only be time consuming and it's gonna be endless.

**Comment by jasonlemay** [comment]
And, the analytics experiment is over :)
